# Generated by Django 5.2.17 on 2026-10-01 14:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField()),
                ("website", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnicalSkill",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("title", models.CharField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "start_date",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use MM/YYYY or DD/MM/YYYY.",
                                regex="^(0[1-9]|1[0-2])/\\d{4}$|^(0[1-9]|[12]\\d|3[01])/(0[1-9]|1[0-2])/\\d{4}$",
                            )
                        ],
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use MM/YYYY or DD/MM/YYYY.",
                                regex="^(0[1-9]|1[0-2])/\\d{4}$|^(0[1-9]|[12]\\d|3[01])/(0[1-9]|1[0-2])/\\d{4}$",
                            )
                        ],
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_experiences",
                        to="work.company",
                    ),
                ),
                (
                    "soft_skills",
                    models.ManyToManyField(
                        blank=True, related_name="work_experiences", to="work.softskill"
                    ),
                ),
                (
                    "technical_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="work_experiences",
                        to="work.technicalskill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
