# Generated by Django 5.2.17 on 2026-10-01 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("text", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("active", True)),
                        fields=["active"],
                        name="overview_active_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("active",),
                        name="overview_only_one_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField()),
                ("surname", models.CharField()),
                ("birth_date", models.DateField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.Value(1), name="personalinfo_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpokenLanguage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("name", models.CharField()),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LW", "Basso"),
                            ("ML", "Medio-Basso"),
                            ("MD", "Medio"),
                            ("MA", "Medio-Avanzato"),
                            ("AD", "Avanzato"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("active", True)),
                        fields=["active", "name"],
                        name="spokenlanguage_active_name_idx",
                    )
                ],
            },
        ),
    ]
